#pragma once
#define ADC_BYTES_PER_SAMPLE	(2)
#define NUMBER_SAMPLES_PER_READ (2)
#define NUMBER_BYTES_PER_PAGE	(4096)
#define BYTES_PER_DEVICE		(1 << 23)
#define NUMBER_READS_PER_DEVICE (BYTES_PER_DEVICE / (NUMBER_SAMPLES_PER_READ*ADC_BYTES_PER_SAMPLE))
#define NUMBER_PAGES_PER_DEVICE (NUMBER_BYTES_PER_PAGE / BYTES_PER_DEVICE)
#define READ_BUFFER_SIZE		(NUMBER_BYTES_PER_PAGE / ADC_BYTES_PER_SAMPLE)